### ISSUE TITLE
Error on first use

### ISSUE THREAD

**Issue by shinze** [theclimber/Bilboplanet#8]
After installation process this message is shown when I try to get on Bilboplanet homepage.
I’m on a brand new MampPro installation on OS X Lion.

```
Fatal error: Uncaught exception 'Exception' with message 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as total_score FROM bp_post, bp_user, bp_post_share WHERE bp_user.user_id = ' at line 16 (1064)' in /Users/me/Sites/Bilboplanet/inc/clearbricks/dblayer/class.mysql.php:105 Stack trace: #0 /Users/me/Sites/Bilboplanet/inc/clearbricks/dblayer/dblayer.php(311): mysqlConnection->db_query(Resource id #15, 'SELECT DISTINCT...') #1 /Users/me/Sites/Bilboplanet/inc/fonctions.php(645): dbLayer->select('SELECT DISTINCT...') #2 /Users/me/Sites/Bilboplanet/portal.php(72): showTribe('SELECT DISTINCT...', tre) #3 /Users/me/Sites/Bilboplanet/index.php(50): require_once('/Users/me/S...') #4 {main} thrown in /Users/me/Sites/Bilboplanet/inc/clearbricks/dblayer/class.mysql.php on line 105
```

**Comment by theclimber** [comment]
Thank you for this bug report.
I'll have a look

**Comment by theclimber** [comment]
Hi,
I commited a bug fix for this problem. It should now work with the latest version :
https://github.com/theclimber/Bilboplanet/commit/7be6bfd19d4d470dbbf92794b40c14f65b5112fb

I hope this helps

**Comment by theclimber** [comment]
Can you tell me if this resolves the problem? Thank you
